<?xml version="1.0" encoding="utf-8"?><Database Name="Erehwon" Class="ErehwonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Erehwon.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ErehwonConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Client_Order" Member="Orders" ThisKey="ClientID" OtherKey="ClientID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Purchase" Member="Purchases" ThisKey="OrderID" OtherKey="OrderID" Type="Purchase" />
      <Association Name="Client_Order" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="PurchaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlotID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountPaid" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Order_Purchase" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Plot_Purchase" Member="Plot" ThisKey="PlotID" OtherKey="PlotID" Type="Plot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlotCategory" Member="PlotCategories">
    <Type Name="PlotCategory">
      <Column Name="PlotCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlotCategoryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlotCategoryDescription" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="TotalHectares" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PlotCategory_Plot" Member="Plots" ThisKey="PlotCategoryID" OtherKey="PlotCategoryID" Type="Plot" />
    </Type>
  </Table>
  <Table Name="dbo.Plot" Member="Plots">
    <Type Name="Plot">
      <Column Name="PlotID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlotName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlotDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlotCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalHectares" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Plot_Purchase" Member="Purchases" ThisKey="PlotID" OtherKey="PlotID" Type="Purchase" />
      <Association Name="PlotCategory_Plot" Member="PlotCategory" ThisKey="PlotCategoryID" OtherKey="PlotCategoryID" Type="PlotCategory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>